-- SQL script to create 10 test users for the Inner Circle app
-- Run this in the Supabase SQL Editor

-- Create 10 test users with realistic entrepreneur profiles
INSERT INTO public.users (
  id,
  email,
  name,
  bio,
  location,
  zip_code,
  latitude,
  longitude,
  business_field,
  entrepreneur_status,
  photo_url,
  membership_tier,
  business_verified,
  joined_groups,
  created_at,
  skills_offered,
  skills_seeking,
  industry_focus,
  business_stage,
  key_challenge,
  availability_level,
  timezone,
  success_highlight,
  looking_for
) VALUES 
-- User 1: Tech Startup Founder
(
  gen_random_uuid(),
  'sarah.tech@example.com',
  'Sarah Chen',
  'Building the next generation of AI-powered productivity tools. Former Google PM with 8+ years in tech.',
  'San Francisco, CA',
  '94102',
  37.7749,
  -122.4194,
  'Technology',
  'current',
  'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400',
  'gold',
  true,
  ARRAY[]::uuid[],
  extract(epoch from now()) * 1000,
  ARRAY['Product Management', 'AI/ML', 'Fundraising'],
  ARRAY['Marketing', 'Sales'],
  'SaaS',
  'Growth Stage',
  'Scaling customer acquisition while maintaining product quality',
  ARRAY['Regular virtual coffee', 'Local meetups'],
  'America/Los_Angeles',
  'Secured $2M Series A funding',
  ARRAY['Partners', 'Mentor', 'Peers']
),

-- User 2: FinTech Entrepreneur
(
  gen_random_uuid(),
  'mike.fintech@example.com',
  'Mike Rodriguez',
  'Revolutionizing digital banking for small businesses. Previously built payment systems at Stripe.',
  'New York, NY',
  '10001',
  40.7128,
  -74.0060,
  'Finance',
  'current',
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
  'silver',
  true,
  ARRAY[]::uuid[],
  extract(epoch from now()) * 1000,
  ARRAY['Finance', 'Payments', 'Regulatory Compliance'],
  ARRAY['UI/UX', 'Customer Service'],
  'FinTech',
  'Pre-Seed/Startup',
  'Navigating complex financial regulations',
  ARRAY['Quick chats', 'Regular virtual coffee'],
  'America/New_York',
  'Processed $10M in transactions',
  ARRAY['Mentor', 'Bounce Ideas', 'Funding']
),

-- User 3: Health Tech Founder
(
  gen_random_uuid(),
  'dr.emma@example.com',
  'Dr. Emma Thompson',
  'Physician-turned-entrepreneur building telemedicine solutions for rural communities.',
  'Austin, TX',
  '73301',
  30.2672,
  -97.7431,
  'Health',
  'current',
  'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400',
  'bronze',
  false,
  ARRAY[]::uuid[],
  extract(epoch from now()) * 1000,
  ARRAY['Healthcare', 'Clinical Operations', 'Patient Care'],
  ARRAY['Marketing', 'Sales', 'Development'],
  'HealthTech',
  'Idea Phase',
  'Getting insurance companies to cover our services',
  ARRAY['Long-term mentorship/partnership'],
  'America/Chicago',
  'Helped 1000+ patients access care remotely',
  ARRAY['Partners', 'Mentoring others', 'Meetups']
),

-- User 4: E-commerce Entrepreneur
(
  gen_random_uuid(),
  'alex.shop@example.com',
  'Alex Johnson',
  'Building sustainable fashion marketplace connecting eco-conscious consumers with ethical brands.',
  'Portland, OR',
  '97201',
  45.5152,
  -122.6784,
  'E-commerce',
  'upcoming',
  'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
  'bronze',
  false,
  ARRAY[]::uuid[],
  extract(epoch from now()) * 1000,
  ARRAY['E-commerce', 'Supply Chain', 'Sustainability'],
  ARRAY['Marketing', 'Fundraising'],
  'Fashion',
  'Pre-Seed/Startup',
  'Building trust with both consumers and brands',
  ARRAY['Quick chats', 'Local meetups'],
  'America/Los_Angeles',
  'Launched with 50+ sustainable brands',
  ARRAY['Partners', 'Bounce Ideas', 'Funding']
),

-- User 5: EdTech Founder
(
  gen_random_uuid(),
  'prof.david@example.com',
  'David Kim',
  'Former professor creating adaptive learning platforms for K-12 education.',
  'Boston, MA',
  '02101',
  42.3601,
  -71.0589,
  'Education',
  'current',
  'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400',
  'silver',
  true,
  ARRAY[]::uuid[],
  extract(epoch from now()) * 1000,
  ARRAY['Education', 'Curriculum Design', 'Data Analysis'],
  ARRAY['Sales', 'Marketing', 'Operations'],
  'EdTech',
  'Growth Stage',
  'Scaling to serve more school districts',
  ARRAY['Regular virtual coffee', 'Long-term mentorship/partnership'],
  'America/New_York',
  'Serving 100+ schools across 5 states',
  ARRAY['Mentor', 'Peers', 'Meetups']
),

-- User 6: Food & Beverage Entrepreneur
(
  gen_random_uuid(),
  'chef.maria@example.com',
  'Maria Santos',
  'Chef turned entrepreneur building a network of ghost kitchens for delivery-only restaurants.',
  'Miami, FL',
  '33101',
  25.7617,
  -80.1918,
  'Food & Beverage',
  'upcoming',
  'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400',
  'bronze',
  false,
  ARRAY[]::uuid[],
  extract(epoch from now()) * 1000,
  ARRAY['Culinary Arts', 'Restaurant Operations', 'Food Safety'],
  ARRAY['Marketing', 'Sales', 'Development'],
  'Food & Beverage',
  'Idea Phase',
  'Managing multiple kitchen operations efficiently',
  ARRAY['Quick chats', 'Local meetups'],
  'America/New_York',
  'Successfully launched 3 virtual restaurant brands',
  ARRAY['Partners', 'Bounce Ideas', 'Meetups']
),

-- User 7: Real Estate Tech
(
  gen_random_uuid(),
  'james.realestate@example.com',
  'James Wilson',
  'Real estate agent building tech solutions to streamline property transactions.',
  'Denver, CO',
  '80202',
  39.7392,
  -104.9903,
  'Real Estate',
  'current',
  'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
  'gold',
  true,
  ARRAY[]::uuid[],
  extract(epoch from now()) * 1000,
  ARRAY['Real Estate', 'Sales', 'Negotiation'],
  ARRAY['Development', 'UI/UX'],
  'Real Estate',
  'Established/Scaling',
  'Integrating with existing real estate systems',
  ARRAY['Regular virtual coffee', 'Local meetups'],
  'America/Denver',
  'Closed $50M in property transactions',
  ARRAY['Mentor', 'Peers', 'Meetups']
),

-- User 8: Creative Agency Owner
(
  gen_random_uuid(),
  'lisa.creative@example.com',
  'Lisa Park',
  'Creative director running a boutique design agency specializing in brand identity for startups.',
  'Seattle, WA',
  '98101',
  47.6062,
  -122.3321,
  'Creative',
  'current',
  'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400',
  'silver',
  false,
  ARRAY[]::uuid[],
  extract(epoch from now()) * 1000,
  ARRAY['Design', 'Brand Strategy', 'Content Creation'],
  ARRAY['Sales', 'Operations', 'Finance'],
  'Creative',
  'Growth Stage',
  'Balancing creative work with business development',
  ARRAY['Quick chats', 'Regular virtual coffee'],
  'America/Los_Angeles',
  'Designed brands for 200+ successful startups',
  ARRAY['Partners', 'Mentor', 'Peers']
),

-- User 9: Consulting Entrepreneur
(
  gen_random_uuid(),
  'robert.consulting@example.com',
  'Robert Chen',
  'Management consultant helping small businesses scale through operational efficiency.',
  'Chicago, IL',
  '60601',
  41.8781,
  -87.6298,
  'Consulting',
  'current',
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
  'bronze',
  false,
  ARRAY[]::uuid[],
  extract(epoch from now()) * 1000,
  ARRAY['Operations', 'Strategy', 'Process Improvement'],
  ARRAY['Marketing', 'Sales'],
  'Consulting',
  'Established/Scaling',
  'Finding the right clients who value strategic consulting',
  ARRAY['Long-term mentorship/partnership'],
  'America/Chicago',
  'Helped 50+ businesses increase efficiency by 30%',
  ARRAY['Mentor', 'Peers', 'Meetups']
),

-- User 10: Manufacturing Startup
(
  gen_random_uuid(),
  'anna.manufacturing@example.com',
  'Anna Kowalski',
  'Engineer building sustainable manufacturing solutions for small businesses.',
  'Detroit, MI',
  '48201',
  42.3314,
  -83.0458,
  'Manufacturing',
  'upcoming',
  'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=400',
  'bronze',
  false,
  ARRAY[]::uuid[],
  extract(epoch from now()) * 1000,
  ARRAY['Engineering', 'Manufacturing', 'Quality Control'],
  ARRAY['Sales', 'Marketing', 'Finance'],
  'Manufacturing',
  'Idea Phase',
  'Securing initial manufacturing contracts',
  ARRAY['Quick chats', 'Local meetups'],
  'America/New_York',
  'Developed 3 patented manufacturing processes',
  ARRAY['Partners', 'Bounce Ideas', 'Funding']
);

-- Verify the users were created
SELECT 
  'Created users:' as status,
  COUNT(*) as total_users
FROM public.users 
WHERE email LIKE '%@example.com';

-- Show the created users
SELECT 
  name,
  email,
  business_field,
  entrepreneur_status,
  membership_tier,
  business_verified
FROM public.users 
WHERE email LIKE '%@example.com'
ORDER BY created_at DESC; 